# https://lgtm.com/help/lgtm/customizing-file-classification
path_classifiers:
  plugins:
    - plugins/

extraction:
  javascript:
    # https://lgtm.com/help/lgtm/javascript-extraction#customizing-index
    # The `index` step extracts information from the files in the codebase.
    index:
      # Specify a list of files and folders to exclude from extraction.
      exclude:
<<<<<<< HEAD
        #- bower_components/
        #- docs/assets/js/plugins/
        #- plugins/
=======
        - 
>>>>>>> 991ef7d320fecb7d1c6ace8744b567cdef828f1b
